apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datascraper
  name: configmap-secret-updater
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  resourceNames: ["bruvaxyear", "telegram"]
  verbs: ["update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-cm-s
  namespace: datascraper
subjects:
- kind: ServiceAccount
  name: default 
  namespace: datascraper
roleRef:
  kind: Role 
  name: configmap-secret-updater
  namespace: datascraper
  apiGroup: rbac.authorization.k8s.io