apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datascraper
  name: configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["bruvaxyear"]
  verbs: ["patch","get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-cm-s
  namespace: datascraper
subjects:
  - kind: ServiceAccount
    name: default 
    namespace: datascraper
roleRef:
  kind: Role 
  name: configmap-updater
  apiGroup: rbac.authorization.k8s.io