apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: datascraper
  name: configmap-updater
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["bruvaxyear"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-cm-s
  namespace: datascraper
subjects:
- kind: ServiceAccount
  name: datascraper 
  namespace: datascraper
roleRef:
  kind: Role 
  name: configmap-updater
  namespace: datascraper
  apiGroup: rbac.authorization.k8s.io